parameters:
  dependsOn: ''
  deploymentName: ''
  serviceConnection: ''
  envGroup: ''
  envName: ''
  functionApp: ''
  repository: ''
  rgName: ''
  kvName: ''

jobs:
- deployment: '${{ parameters.deploymentName }}'
  dependsOn: '${{ parameters.dependsOn }}'
  displayName: '${{ parameters.deploymentName }}'
  environment: '${{ parameters.envGroup }}'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none
        - task: AzureCLI@2
          displayName: 'Deploy Function App Test'
          condition: and(succeeded(), eq('${{ parameters.envName }}', 'test'))
          inputs:
            azureSubscription: '${{ parameters.serviceConnection }}'
            scriptLocation: inlineScript
            scriptType: pscore
            inlineScript: |
              # Set Application settings
              az functionapp config appsettings set --resource-group "${{ parameters.rgName }}" --name "${{ parameters.functionApp }}" --settings `
                "MainSecret=@Microsoft.KeyVault(VaultName=${{ parameters.kvName }};SecretName=MainSecretTest)" `
                "PCSUrl=https://procosystest.equinor.com/" `
                "Schedule=0 0 1 * * Mon"

              # Publish application
              az functionapp config container set `
                --resource-group "${{ parameters.rgName }}" `
                --name "${{ parameters.functionApp }}" `
                --docker-registry-server-url https://$(containerRegistryName).azurecr.io `
                --docker-custom-image-name "$(containerRegistryName).azurecr.io/${{ parameters.repository }}:$(Build.BuildId)"

        - task: AzureCLI@2
          displayName: 'Deploy Function App Prod'
          condition: and(succeeded(), eq('${{ parameters.envName }}', 'prod'))
          inputs:
            azureSubscription: '${{ parameters.serviceConnection }}'
            scriptLocation: inlineScript
            scriptType: pscore
            inlineScript: |
              # Set Application settings
              az functionapp config appsettings set --resource-group "${{ parameters.rgName }}" --name "${{ parameters.functionApp }}" --settings `
                "MainSecret=@Microsoft.KeyVault(VaultName=${{ parameters.kvName }};SecretName=MainSecret)" `
                "PCSUrl=https://procosys.equinor.com/" `
                "Schedule=0 0 1 * * Mon"

              # Publish application
              az functionapp config container set `
                --resource-group "${{ parameters.rgName }}" `
                --name "${{ parameters.functionApp }}" `
                --docker-registry-server-url https://$(containerRegistryName).azurecr.io `
                --docker-custom-image-name "$(containerRegistryName).azurecr.io/${{ parameters.repository }}:$(Build.BuildId)"
